### ISSUE TITLE
出现了VAC

### ISSUE THREAD

**Issue by yxb6846928** [djkcyl/CSGO-Hack-Osiris-Chinese-version#10]
最近我用了os的改皮肤源码，出现了VAC。是给v社检测到了吗

**Comment by djkcyl** [comment]
最近的vac更新了，出现vac是注入器的问题，换个注入器试试

**Comment by yxb6846928** [comment]
> 了

我的注入器是没有问题的。我用另一个DLL，同个注入器，那个账号是没有出现VAC的。

**Comment by djkcyl** [comment]
那我就不清楚了，估计是这海王出问题了，我晚点更新吧

**Comment by yxb6846928** [comment]
> 那我就不清楚了，估计是这海王出问题了，我晚点更新吧

兄弟，可以留个联系方式么。有空可以一起交流

**Comment by djkcyl** [comment]
2948531755
