### ISSUE TITLE
在正常环境下运行提示请不要在虚拟机下运行

### ISSUE THREAD

**Issue by BoringYang** [djkcyl/CSGO-Hack-Osiris-Chinese-version#9]
反VAC和注入程序都报这样的错

**Comment by djkcyl** [comment]
有没有装安全软件

**Comment by BoringYang** [comment]
现在关闭win10的虚拟机服务和wsl服务就好了  估计是检测到这个服务就判断为虚拟机环境了 需要改一下这个逻辑



发自我的小米手机在 djkcyl <notifications@github.com>，2020年10月18日 下午7:39写道：

有没有装安全软件



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/djkcyl/CSGO-Hack-Osiris-Chinese-version/issues/9#issuecomment-711155328",

"url": "https://github.com/djkcyl/CSGO-Hack-Osiris-Chinese-version/issues/9#issuecomment-711155328",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by djkcyl** [comment]
ok明白了
